

<form id="pagerForm" method="post" action="log/logList">
	<input type="hidden" name="status" value="${param.status}">
	<input type="hidden" name="keywords" value="${param.keywords}" />
	<input type="hidden" name="pageNum" value="1" />
	<input type="hidden" name="numPerPage" value="<?php echo $numPerPage;?>" />
	<input type="hidden" name="startTime" value="<?php echo @$startTime;?>" />
	<input type="hidden" name="endTime" value="<?php echo @$endtime;?>"/>
</form>
<div class="pageHeader" >
	<form onsubmit="return navTabSearch(this);" action="log/logList" method="post">
	<div class="searchBar">
		<table class="searchContent" >
			<tr>
				<td>
					开始时间：<input type="text" name="startTime" class="date"/>
				</td>
				<td>
					结束时间：<input type="text" name="endTime" class="date"/>
				</td>
				<td>
				<div class="buttonActive"><div class="buttonContent"><button type="submit" >检索</button></div></div>
				</td>
			</tr>
		</table>
	</div>
	</form>
</div>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<!-- <li><a class="add" href="company/addCompany" target="dialog"><span>添加</span></a></li>
			<li><a title="确实要删除这些记录吗?" target="selectedTodo" rel="ids" postType="string" href="company/deleteCompany" class="delete"><span>批量删除</span></a></li>
			<li><a class="edit" href="demo_page4.html?uid={sid_user}" target="dialog" mask="true" warn="请选择用户" ><span>修改</span></a></li>
			<li class="line">line</li>
			<li><a class="icon" href="demo/common/dwz-team.xls" target="dwzExport" targetType="navTab" title="实要导出这些记录吗?"><span>导出EXCEL</span></a></li>-->
		</ul>
	</div>
	<table class="table" width="100%" layoutH="112">
		<thead>
			<tr>
				<th width="10%" align="left">记录编号</th>
				<th width="15%" align="left">操作人</th>
				<th width="15%" align="left">操作时间</th>
				<th width="30%" align="left">操作内容</th>
				<th width="20%" align="left">操作人ip</th>
				<th width="10%" align="left">操作类型</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($page->items as $items){?>
			<tr target="sid_user" rel="">
			    <td><?php echo $items->lid;?></td>
				<td><?php echo $items->userName; ?></td>
				<td><?php echo date("Y-m-d H:i:s",$items->insertTime); ?></td>
				<td><?php echo $items->content; ?></td>
				<td><?php echo long2ip($items->insertIp); ?></td>
				<td><?php echo $items->typeId; ?></td>
				<!-- 
				<td>
				&nbsp;
					<a title="确定要删除吗"  target="ajaxTodo" href="company/deleteCompany?ids=<?php echo $value['companyId']; ?>" class="btnDel">删除</a>
					<a title="编辑"  href="company/editCompany?companyId=<?php echo $value['companyId']; ?>" class="btnEdit" target="dialog" rel="dlg_page9">编辑</a>
					<a class="button" href="demo_page4.html" target="dialog" rel="dlg_page9"><span>打开窗口9</span></a>
				</td>-->
			</tr>
			<?php }?>
		</tbody>
	</table>
	<div class="panelBar">
		<div class="pages">
			 <span>显示</span>
			<select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage:this.value})">
				<option value="20">20</option>
				<option value="50">50</option>
				<option value="100">100</option>
				<option value="200">200</option>
			</select>
			<span>条，共<?php echo $page->total_items;?>条</span>

			
		</div>
		
		<div class="pagination" targetType="navTab" totalCount="<?php echo $page->total_items;?>" numPerPage="<?php echo $numPerPage;?>" pageNumShown="100" currentPage="<?php echo $page->current;?>"></div>

	</div>
</div>
你好,【1沙1天堂】
充值卡号：25-20140420-185144-8000
密码：eba0d4dc65257665419a793ffb11fa9a
开通方法:http://www.idc35.com/help/kongjian/newsbody.asp?id=88
一小时内好评将立即获得价值超过万元的999G赠品发送到您旺旺！

