<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<title>网球管理cms</title>

<link href="css/themes/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="css/themes/css/core.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="css/themes/css/print.css" rel="stylesheet" type="text/css" media="print"/>
<link href="uploadify/css/uploadify.css" rel="stylesheet" type="text/css" media="screen"/>
<!--[if IE]>
<link href="css/themes/css/ieHack.css" rel="stylesheet" type="text/css" media="screen"/>
<![endif]-->
<style type="text/css">
	#header{height:85px}
	#leftside, #container, #splitBar, #splitBarProxy{top:90px}
</style>
<script src="js/dwz/speedup.js" type="text/javascript"></script>
<script src="js/dwz/jquery-1.7.1.js" type="text/javascript"></script>
<script src="js/dwz/jquery.cookie.js" type="text/javascript"></script>
<script src="js/dwz/jquery.validate.js" type="text/javascript"></script>
<script src="js/dwz/jquery.bgiframe.js" type="text/javascript"></script>
<script src="xheditor/xheditor-1.1.12-zh-cn.min.js" type="text/javascript"></script>
<script src="uploadify/scripts/swfobject.js" type="text/javascript"></script>
<script src="uploadify/scripts/jquery.uploadify.v2.1.0.js" type="text/javascript"></script>

<script src="js/dwz/dwz.core.js" type="text/javascript"></script>
<script src="js/dwz/dwz.util.date.js" type="text/javascript"></script>
<script src="js/dwz/dwz.validate.method.js" type="text/javascript"></script>
<script src="js/dwz/dwz.regional.zh.js" type="text/javascript"></script>
<script src="js/dwz/dwz.barDrag.js" type="text/javascript"></script>
<script src="js/dwz/dwz.drag.js" type="text/javascript"></script>
<script src="js/dwz/dwz.tree.js" type="text/javascript"></script>
<script src="js/dwz/dwz.accordion.js" type="text/javascript"></script>
<script src="js/dwz/dwz.ui.js" type="text/javascript"></script>
<script src="js/dwz/dwz.theme.js" type="text/javascript"></script>
<script src="js/dwz/dwz.switchEnv.js" type="text/javascript"></script>
<script src="js/dwz/dwz.alertMsg.js" type="text/javascript"></script>
<script src="js/dwz/dwz.contextmenu.js" type="text/javascript"></script>
<script src="js/dwz/dwz.navTab.js" type="text/javascript"></script>
<script src="js/dwz/dwz.tab.js" type="text/javascript"></script>
<script src="js/dwz/dwz.resize.js" type="text/javascript"></script>
<script src="js/dwz/dwz.dialog.js" type="text/javascript"></script>
<script src="js/dwz/dwz.dialogDrag.js" type="text/javascript"></script>
<script src="js/dwz/dwz.sortDrag.js" type="text/javascript"></script>
<script src="js/dwz/dwz.cssTable.js" type="text/javascript"></script>
<script src="js/dwz/dwz.stable.js" type="text/javascript"></script>
<script src="js/dwz/dwz.taskBar.js" type="text/javascript"></script>
<script src="js/dwz/dwz.ajax.js" type="text/javascript"></script>
<script src="js/dwz/dwz.pagination.js" type="text/javascript"></script>
<script src="js/dwz/dwz.database.js" type="text/javascript"></script>
<script src="js/dwz/dwz.datepicker.js" type="text/javascript"></script>
<script src="js/dwz/dwz.effects.js" type="text/javascript"></script>
<script src="js/dwz/dwz.panel.js" type="text/javascript"></script>
<script src="js/dwz/dwz.checkbox.js" type="text/javascript"></script>
<script src="js/dwz/dwz.history.js" type="text/javascript"></script>
<script src="js/dwz/dwz.combox.js" type="text/javascript"></script>
<script src="js/dwz/dwz.print.js" type="text/javascript"></script>
<script src="xheditor/xheditor-1.1.12-zh-cn.min.js" type="text/javascript"></script>
<script src="uploadify/scripts/swfobject.js" type="text/javascript"></script>
<script src="uploadify/scripts/jquery.uploadify.v2.1.0.js" type="text/javascript"></script>

<script src="bin/dwz.min.js" type="text/javascript"></script>
<script src="js/dwz/dwz.regional.zh.js" type="text/javascript"></script>

<!--
<script src="bin/dwz.min.js" type="text/javascript"></script>
-->

<script type="text/javascript">
$(function(){
	DWZ.init("dwz.frag.xml", {
		loginUrl:"login_dialog.html", loginTitle:"登录",	// 弹出登录对话框
//		loginUrl:"login.html",	// 跳到登录页面
		statusCode:{ok:200, error:300, timeout:301}, //【可选】
		pageInfo:{pageNum:"pageNum", numPerPage:"numPerPage", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
		debug:false,	// 调试模式 【true|false】
		callback:function(){
			initEnv();
			$("#themeList").theme({themeBase:"themes"}); // themeBase 相对于index页面的主题base路径
			
		}
	});
});
</script>

</head>

<body scroll="no">
	<div id="layout">
		<div id="header">
			<div class="headerNav">
				<a class="logo" href="http://j-ui.com">标志</a>
				<ul class="nav" >
					<li id="switchEnvBox" style="line-height:15px"><a href="javascript:">（<span>北京</span>）切换城市</a>
						<ul>
							<li><a href="sidebar_1.html">北京</a></li>
							<li><a href="sidebar_2.html">上海</a></li>
							<li><a href="sidebar_2.html">南京</a></li>
							<li><a href="sidebar_2.html">深圳</a></li>
							<li><a href="sidebar_2.html">广州</a></li>
							<li><a href="sidebar_2.html">天津</a></li>
							<li><a href="sidebar_2.html">杭州</a></li>
						</ul>
					</li>
					<li style="line-height:15px"><a href="https://me.alipay.com/dwzteam" target="_blank">捐赠</a></li>
					<li style="line-height:15px"><a href="changepwd.html" target="dialog" width="600">设置</a></li>
					<li style="line-height:15px"><a href="http://www.cnblogs.com/dwzjs" target="_blank">博客</a></li>
					<li style="line-height:15px"><a href="http://weibo.com/dwzui" target="_blank">微博</a></li>
					<li style="line-height:15px"><a href="http://bbs.dwzjs.com" target="_blank">论坛</a></li>
					<li style="line-height:15px"><a href="login.html">退出</a></li>
				</ul>
				<ul class="themeList" id="themeList">
					<li theme="default"><div class="selected">蓝色</div></li>
					<li theme="green"><div>绿色</div></li>
					<!--<li theme="red"><div>红色</div></li>-->
					<li theme="purple"><div>紫色</div></li>
					<li theme="silver"><div>银色</div></li>
					<li theme="azure"><div>天蓝</div></li>
				</ul>
			</div>
				<div id="navMenu">
				<ul>
					<li class="selected"><a href=""><span>全部</span></a></li>
					<li><a href=""><span>公司管理</span></a></li>
					<li><a href=""><span>场地管理</span></a></li>
					<li><a href=""><span>图片管理</span></a></li>
					<li><a href=""><span>日志管理</span></a></li>
					<li><a href=""><span>系统设置</span></a></li>
				</ul>
			</div>
			<!-- navMenu -->
			
		</div>

		<div id="leftside">
			<div id="sidebar_s">
				<div class="collapse">
					<div class="toggleCollapse"><div></div></div>
				</div>
			</div>
			<div id="sidebar">
				<div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>

				<div class="accordion" fillSpace="sidebar">
					<div class="accordionHeader">
						<h2><span>Folder</span>界面组件</h2>
					</div>
					<div class="accordionContent">
						<ul class="tree treeFolder">
							<li><a target="navTab">公司管理</a>
								<ul>
									<li><a href="company/companyList" target="navTab" rel="navCompanyList">公司列表</a></li>
								</ul>
							</li>
							
							<li><a>场地管理</a>
								<ul>
									<li><a href="stadium/stadiumList" target="navTab" rel="navStadiumList">场地列表</a></li>
								</ul>
							</li>
									
							<li><a>图片管理</a>
								<ul>
									<li><a href="picture/addpicture" target="navTab" rel="navAddPicture">添加图片</a></li>
									<li><a href="picture/pictureList" target="navTab" rel="navPictureList">图片列表</a></li>
								</ul>
							</li>
							<li><a>文章管理</a>
								<ul>
									<li><a href="article/addArticle" target="navTab" rel="navAddArticle">添加文章</a></li>
									<li><a href="article/articleList" target="navTab" rel="navArticleList">文章列表</a></li>
									</ul>
							</li>
							
							<li><a>日志管理</a>
								<ul>
									<li><a href="log/logList" target="navTab" rel="navLogList">日志列表</a></li>
									</ul>
							</li>
							<li><a href="dwz.frag.xml" target="navTab" external="true">dwz.frag.xml</a></li>
						</ul>
					</div>
					<div class="accordionHeader">
						<h2><span>Folder</span>典型页面</h2>
					</div>
					<div class="accordionContent">
						<ul class="tree treeFolder treeCheck">
							<li><a href="demo_page1.html" target="navTab" rel="demo_page1">查询我的客户</a></li>
							<li><a href="demo_page1.html" target="navTab" rel="demo_page2">表单查询页面</a></li>
							<li><a href="demo_page4.html" target="navTab" rel="demo_page4">表单录入页面</a></li>
							<li><a href="demo_page5.html" target="navTab" rel="demo_page5">有文本输入的表单</a></li>
							<li><a href="javascript:;">有提示的表单输入页面</a>
								<ul>
									<li><a href="javascript:;">页面一</a></li>
									<li><a href="javascript:;">页面二</a></li>
								</ul>
							</li>
							<li><a href="javascript:;">选项卡和图形的页面</a>
								<ul>
									<li><a href="javascript:;">页面一</a></li>
									<li><a href="javascript:;">页面二</a></li>
								</ul>
							</li>
							<li><a href="javascript:;">选项卡和图形切换的页面</a></li>
							<li><a href="javascript:;">左右两个互动的页面</a></li>
							<li><a href="javascript:;">列表输入的页面</a></li>
							<li><a href="javascript:;">双层栏目列表的页面</a></li>
						</ul>
					</div>
					<div class="accordionHeader">
						<h2><span>Folder</span>流程演示</h2>
					</div>
					<div class="accordionContent">
						<ul class="tree">
							<li><a href="newPage1.html" target="dialog" rel="dlg_page">列表</a></li>
							<li><a href="newPage1.html" target="dialog" rel="dlg_page2">列表</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="container">
			<div id="navTab" class="tabsPage" layoutH="120px">
				<div class="tabsPageHeader">
					<div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
						<ul class="navTab-tab">
							<li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
						</ul>
					</div>
					<div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
					<div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
					<div class="tabsMore">more</div>
				</div>
				<ul class="tabsMoreList">
					<li><a href="javascript:;">我的主页</a></li>
				</ul>
				<div class="navTab-panel tabsPageContent layoutBox"  layoutH="800px">
					<div class="page unitBox"  >
						<div class="accountInfo">
							<div class="alertInfo">
								<h2><a href="doc/dwz-user-guide.pdf" target="_blank">DWZ框架使用手册(PDF)</a></h2>
								<a href="doc/dwz-user-guide.swf" target="_blank">DWZ框架演示视频</a>
							</div>
							<div class="right">
								<p><a href="doc/dwz-user-guide.zip" target="_blank" style="line-height:19px">DWZ框架使用手册(CHM)</a></p>
								<p><a href="doc/dwz-ajax-develop.swf" target="_blank" style="line-height:19px">DWZ框架Ajax开发视频教材</a></p>
							</div>
							<p><span>DWZ富客户端框架</span></p>
							<p>DWZ官方微博:<a href="http://weibo.com/dwzui" target="_blank">http://weibo.com/dwzui</a></p>
						</div>
						<div class="pageFormContent" layoutH="800" style="margin-right:230px">
							
							<p style="color:red">DWZ官方微博 <a href="http://weibo.com/dwzui" target="_blank">http://weibo.com/dwzui</a></p>
							<p style="color:red">DWZ官方微群 <a href="http://q.weibo.com/587328/invitation=11TGXSt-148c2" target="_blank">http://q.weibo.com/587328/invitation=11TGXSt-148c2</a></p>

<div class="divider"></div>
<h2>dwz v1.2视频教程:</h2>
<p><a href="http://www.u-training.com/thread-57-1-1.html" target="_blank">http://www.u-training.com/thread-57-1-1.html</a></p>

<div class="divider"></div>
<h2>DWZ系列开源项目:</h2>
<div class="unit"><a href="http://code.google.com/p/dwz/" target="_blank">dwz富客户端框架 - jUI</a></div>
<div class="unit"><a href="http://code.google.com/p/dwz4j" target="_blank">dwz4j(Java Web)快速开发框架 + jUI整合应用</a></div>
<div class="unit"><a href="http://code.google.com/p/j-hi" target="_blank">J-HI(Java Web)快速开发平台 + jUI整合应用（Eclipse插件生成项目代码）</a></div>
<div class="unit"><a href="http://code.google.com/p/dwz4php" target="_blank">ThinkPHP2.1 + jUI整合应用</a></div>
<div class="unit"><a href="http://www.yiiframework.com/extension/dwzinterface/" target="_blank">YII + jUI整合应用</a></div>

<div class="divider"></div>
<h2>常见问题及解决:</h2>
<pre style="margin:5px;line-height:1.4em">
Error loading XML document: dwz.frag.xml
直接用IE打开index.html弹出一个对话框：Error loading XML document: dwz.frag.xml
原因：没有加载成功dwz.frag.xml。IE ajax laod本地文件有限制, 是ie安全级别的问题, 不是框架的问题。
解决方法：用firefox打开或部署到apache下。
</pre>

<div class="divider"></div>
<h2>有偿服务请联系:</h2>
<pre style="margin:5px;line-height:1.4em;">
定制化开发，公司培训，技术支持
合作电话：010-52897073
邮箱：support@dwzjs.com
</pre>
						</div>
					</div>
					
				</div>
			</div>
		</div>

	</div>

	<div id="footer">Copyright &copy; 2010 <a href="demo_page2.html" target="dialog">DWZ团队</a> Tel：010-52897073</div>



</body>
</html>