<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>系统后台管理</title>
<link href="/Css/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/Css/css/core.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/Css/css/print.css" rel="stylesheet" type="text/css" media="print"/>
<link href="/Js/uploadify/css/uploadify.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/Css/system.css" rel="stylesheet" type="text/css" media="screen"/>
<!--[if IE]>
<link href="/Css/css/ieHack.css" rel="stylesheet" type="text/css" media="screen"/>
<![endif]-->
<script src="/Js/speedup.js" type="text/javascript"></script>
<script src="/Js/jquery.js" type="text/javascript"></script>
<script src="/Js/jquery.cookie.js" type="text/javascript"></script>
<script src="/Js/jquery.validate.js" type="text/javascript"></script>
<script src="/Js/jquery.validate.messages_cn.js" type="text/javascript"></script>
<script src="/Js/jquery.bgiframe.js" type="text/javascript"></script>
<script src="/Js/xheditor/xheditor-1.1.12-zh-cn.min.js" type="text/javascript"></script>
<script src="/Js/uploadify/scripts/swfobject.js" type="text/javascript"></script>
<script src="/Js/uploadify/scripts/jquery.uploadify.v2.1.0.js" type="text/javascript"></script>
<script src="/Js/dwz.min.js" type="text/javascript"></script>
<script src="/Js/dwz.regional.zh.js" type="text/javascript"></script>
<script type='text/javascript'>
var app='__APP__';
</script>
<script src="/Js/common.js" type="text/javascript"></script>
<script src="/Js/ocx/call_main.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
	DWZ.init("/dwz.frag.xml", {
		loginUrl:"login_dialog.html", loginTitle:"登录",	// 弹出登录对话框
//		loginUrl:"login.html",	// 跳到登录页面
		//statusCode:{ok:200, error:300, timeout:301}, //【可选】
		statusCode:{ok:1,error:0},
		pageInfo:{pageNum:"pageNum", numPerPage:"numPerPage", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
		debug:false,	// 调试模式 【true|false】
		callback:function(){
			initEnv();
			$("#themeList").theme({themeBase:"/Css"}); // themeBase 相对于index页面的主题base路径
		}
	});
});
</script>
</head>
<body scroll="no">
<div id="layout">
<!-- top -->
<div id="header">
<div class="headerNav">
<a class="logo">标志</a>

<ul class="nav">
<li><a>{$_SESSION.loginaccount}</a></li>
<li><a href="/system.php?m=System&a=clearCache" target="ajaxTodo">清除缓存</a></li>
<li><a href="__APP__?m=Public&a=Logout">退出</a></li>
</ul>
<ul class="themeList" id="themeList">
<li theme="default"><div class="selected">蓝色</div></li>
<li theme="green"><div>绿色</div></li>
<!--<li theme="red"><div>红色</div></li>-->
<li theme="purple"><div>紫色</div></li>
<li theme="silver"><div>银色</div></li>
<li theme="azure"><div>天蓝</div></li>
</ul>
</div>
<!-- navMenu -->
</div>
<!-- top end -->
<!-- left -->
<div id="leftside">
<div id="sidebar_s">
<div class="collapse">
<div class="toggleCollapse"><div></div></div>
</div>
</div>
<div id="sidebar">
<div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>
<!--主菜单-->
<div class="accordion" fillSpace="sidebar">
<foreach name="arrTree.1" item="vo">
<div class="accordionHeader">
<h2><span>Folder</span>{$vo.name}</h2>
</div>
<div class="accordionContent">
<ul class="tree treeFolder">
<foreach name="arrTree[2][$vo[id]]" item="vo2">
<notempty name="arrTree[2][$vo2[id]]">
<li><a>{$vo2.name}</a>
                  <ul>
                     <foreach name="arrTree[2][$vo2[id]]" item="vo3">
                     <li><a href="__APP__{$vo3.url}&pgid=pg{$vo3.id}" target="{$vo3.target}" rel="pg{$vo3.id}">{$vo3.name}</a></li>
                     </foreach>
                  </ul>
                  </li>
<else />
<li><a href="__APP__{$vo2.url}&pgid=pg{$vo2.id}" target="{$vo2.target}" rel="pg{$vo2.id}">{$vo2.name}</a></li>
</notempty>
</foreach>
</ul>
</div>           
</foreach>
</div>
<!--主菜单结束-->
</div>
</div>
<!-- left end -->
<!-- right -->
<div id="container">
			<div id="navTab" class="tabsPage">
				<div class="tabsPageHeader">
					<div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
						<ul class="navTab-tab">
							<li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
						</ul>
					</div>
					<div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
					<div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
					<div class="tabsMore">more</div>
				</div>
				<ul class="tabsMoreList">
					<li><a href="javascript:;">我的主页</a></li>
				</ul>
				<div class="navTab-panel tabsPageContent layoutBox">
					<div class="page unitBox">
<!-- 主页内容 -->				
<!-- 主页内容结束 -->	
					</div>
				</div>
			</div>
		</div>
</div>
<!-- right end -->	
<div id="footer">Copyright &copy; 2010 </div>
</body>
</html>