<form id="pagerForm" method="post" action="article/articleList">
	<input type="hidden" name="status" value="${param.status}">
	<input type="hidden" name="keywords" value="${param.keywords}" />
	<input type="hidden" name="pageNum" value="1" />
	<input type="hidden" name="numPerPage" value="<?php echo $numPerPage;?>" />
	<input type="hidden" name="artTitle" value="<?php echo @$artTitle;?>" />	
	<input type="hidden" name="artAuthor" value="<?php echo @$artAuthor;?>" />	
	<input type="hidden" name="startDate" value="<?php echo @$startDate;?>" />
	<input type="hidden" name="endDate" value="<?php echo @$endDate;?>" />
</form>
<script type="text/javascript">
function dialogAjax(json){
$.pdialog.reloadDialog("triggerList");
}
</script>

<div class="pageHeader" >
	<form onsubmit="return navTabSearch(this);" action="article/articleList" method="post">
	<div class="searchBar">
		<table class="searchContent" >
			<tr>
				<td>
					文章标题：<input type="text" name="artTitle" />
				</td>
				<td>
					文章作者：<input type="text" name="artAuthor" />
				</td>
				<td>
					开始日期：<input type="text" name="startDate" id="startDate" class='date'/>
				</td>
				<td>
					结束日期：<input type="text" name="endDate" id="endDate" class='date' />
				</td>
				<td>
				<div class="buttonActive">
				<div class="buttonContent">
				<button type="submit" >检索</button>
				</div>
				</div>
				</td>
			</tr>
		</table>
	</div>
	</form>
</div>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" href="article/addArticle" target="dialog"><span>添加</span></a></li>
			<li><a title="确实要删除这些记录吗?" target="selectedTodo" rel="ids" postType="string" href="article/deleteArticle" class="delete"><span>批量删除</span></a></li>
			<li><a class="edit" href="demo_page4.html?uid={sid_user}" target="dialog" mask="true" warn="请选择用户" ><span>修改</span></a></li>
			<li class="line">line</li>
			<li><a class="icon" href="demo/common/dwz-team.xls" target="dwzExport" targetType="navTab" title="实要导出这些记录吗?"><span>导出EXCEL</span></a></li>
		</ul>
	</div>
	<table class="table" width="100%" layoutH="112">
		<thead>
			<tr>
				<th width="10%" align="left"><input type="checkbox" group="ids" class="checkboxCtrl"></th>
				<th width="10%" align="left">文章编号</th>
				<th width="20%" align="left">文章标题</th>
				<th width="20%" align="left">文章作者</th>
				<th width="20%" align="left">发布时间</th>
				<th width="20" align="left">操作</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($page->items as $items){?>
			<tr target="rid" rel="<?php echo $items->artId; ?>">
			    <td><input name="ids" value="<?php echo $items->artId; ?>" type="checkbox"></td>
				<td><?php echo $items->artId; ?></td>
				<td><?php echo $items->artTitle; ?></td>
				<td><?php echo $items->artAuthor; ?></td>
				<td><?php echo $items->artTime; ?></td>
				<td>
				&nbsp;
					<a title="确定要删除吗"  target="ajaxTodo"  href="article/deleteArticle?ids=<?php echo $items->artId; ?>" class="btnDel">删除</a>
					<a title="编辑"  href="article/editArticle?artId=<?php echo $items->artId; ?>" class="btnEdit" target="dialog" rel="dlg_page9" width="1000" height="600">编辑</a>
					</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
	<div class="panelBar" >
		<div class="pages">
			 <span>显示</span>
			<select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage:this.value})">
				<option value="20">20</option>
				<option value="50">50</option>
				<option value="100">100</option>
				<option value="200">200</option>
			</select>
			<span>条，共<?php echo $page->total_items;?>条</span>			
		</div>		
		<div class="pagination" targetType="navTab" totalCount="<?php echo $page->total_items;?>" numPerPage="<?php echo $numPerPage;?>" pageNumShown="100" currentPage="<?php echo $page->current;?>"></div>

	</div>
</div>
