<div class="pageContent">
	<form method="post" action="picture/editPicInfoFunc" enctype="multipart/form-data"class="pageForm required-validate" onsubmit="return iframeCallback(this,dialogAjaxDone);">
		<div class="pageFormContent" layoutH="56">
			<p>
				<table cellpadding="0" cellspacing="0" class="l-table-edit" >
            <tr>
                <td align="right" class="l-table-edit-td">所属场馆 :</td>
                <td align="left" class="l-table-edit-td">
                <select name="stadiumId">
                <?php 
                foreach ($stadiumList as $key => $value) {
                	if($pictureInfo['stadiumId']==$key){
                    	echo '<option value="'.$key.'" selected>'.$value.'</option>';
					}
					else{
						echo '<option value="'.$key.'" >'.$value.'</option>';
					}
                }
                
                ?>
                </select>
                	<td align="left"></td>
            </tr>
             <tr>
                <td align="right" class="l-table-edit-td">原图:</td>
                <td align="left" class="l-table-edit-td">
                <?php echo '<img src="images/'.$pictureInfo["picUrl"].'" width="100" height="100"/>';?>
                <td align="left"></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td">修改图片:</td>
                <td align="left" class="l-table-edit-td">
                <input type="file" name="picture" />
                <input  type='hidden' name="picId" value="<?php echo $pictureInfo['picId'];?>"/>
 				<input type="hidden" name="oldpicUrl" value="<?php echo $pictureInfo['picUrl'];?>" />
 				<input type="hidden" name="userId" value="<?php echo'2'; ?>" />
 				<input type="hidden" name="userIp" value="<?php echo'0000000';?>" />
 				<input type="hidden" name="sub" value="提交" />
                <td align="left"></td>
            </tr>
        </table>
        </p>
		</div>
		<div class="formBar">
		<ul>
				<!--<li><a class="buttonActive" href="javascript:;"><span>保存</span></a></li>-->
				<li>
				<div class="buttonActive">
				<div class="buttonContent">
				<button type="submit">保存</button></div></div></li>
				<li>
					<div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
				</li>
			</ul>
	</form>
</div>















