
<div class="pageContent">
	<form method="post" action="company/editCompanyFunc" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone)">
		<div class="pageFormContent" layoutH="56">
			<p>
				<label>公司名称:</label>
				<input type="hidden" name="companyId" value="<?php echo $companyInfo['companyId'];?>">
				<input type="text" name="companyName" class= "require" validate="{required:true,minlength:3,maxlength:10}"value="<?php echo $companyInfo['companyName'];?>">
               </p>
		</div>
		<div class="formBar">
			<ul>
				<!--<li><a class="buttonActive" href="javascript:;"><span>保存</span></a></li>-->
				<li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
				<li>
					<div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
				</li>
			</ul>
		</div>
	</form>
</div>














